### PR TITLE
fixed typing import and fixed _nvar value

### PR DESCRIPTION
**Pull request by peeplika**
resolves #549

### CODE REVIEW

**Comment by liadomide** [comment]
Hi @peeplika,

Thank you for your interest into TVB!

This repo ([tvb-library](https://github.com/the-virtual-brain/tvb-library)) has been declared deprecated. 
All the code was move here https://github.com/the-virtual-brain/tvb-root/tree/master/tvb_library 
Please have a look if the patch is still relevant there (I guess not), or otherwise redirect your efforts towards that repo directly.

**Comment by peeplika** [comment]
okay , Hey there are issues here as well on jira for the project ,are the github issues still relevant , and should I contribute to them ??

**Comment by liadomide** [comment]
In general, both  Github and Jira issues are still relevant.
Although it might be that some old reported ones in either of these system is no longer valid.
We welcome contributions, so please browse through them and let us know if you need support in understanding the descriptions.

**Comment by peeplika** [comment]
Thank you for your response, I was actually trying to understand this issue https://github.com/the-virtual-brain/tvb-root/issues/544 ,Would it be possible for you to provide me with more information on this?

**Pull request closed without merging**
