### PR TITLE
Fixes to the 2 state wong wang model

### PR DESCRIPTION
**Pull request by dokato**
I made a simple modifications (following suggestions of Marmaduke from mailing list) to make Wong-Wang model from contrib running. I had to modify as well is the `phase_plane_interactive.py` script, as it was using deprecated `axisbg` parameter from matplotlib.

### CODE REVIEW

**Comment by maedoc** [comment]
> I made a simple modifications

looks fine to me, thanks!

> using deprecated axisbg parameter from matplotlib

are you running the TVB distribution or your own conda environment?  the TVB packages use a slightly older version of matplotlib for compatibility with some of our older code, I don't want that to break.. @liadomide any thoughts?

**Comment by dokato** [comment]
> are you running the TVB distribution or your own conda environment?

Yeap, I'm using custom env with matplotlib version `2.2.3`. If you indeed think that it's better not to upgrade this please let me know and I'll revoke the changes on `phase_plane_interactive`.

**Comment by maedoc** [comment]
@dokato let's drop the `axisbg` changes for now, so that we can merge the fix for the model.   Can you submit the phase plane changes in a separate PR? 

sorry if it seems like overkill for small changes..

**Comment by dokato** [comment]
Sure @maedoc , I reverted the changes. For now, maybe let's not create a new PR since when I run the scripts from distribution version of python with matplotlib `1.5.0` everything seems to be working just fine.  And as you said, it's better not to break anything. If you decide to upgrade I'd be happy to help.

**Comment by dokato** [comment]
@pausz git tells me that you implemented that WW model. I introduced two minor corrections here, but can't get this to work as in WongWang 2006 paper. I've checked on equations and they look quite okay. Any ideas what might be wrong? Maybe you have some updated version of this?

**Comment by dokato** [comment]
@maedoc as mentioned on the mailing list here's this is my version of a 2D Wong-Wang that reproduces phase planes from 2006 and 2007 articles. I decided to follow the notation from https://www.frontiersin.org/articles/10.3389/neuro.10.006.2007/full as it is easier to follow IMHO.

What it is still lacking are the coupling and local_coupling. I tried to take inspiration from https://github.com/the-virtual-brain/tvb-library/blob/trunk/tvb/simulator/models/wong_wang.py#L184

So it looks that there should be:
```python
c_0 = coupling[0, :]
lc_0_l = local_coupling * sl
lc_0_r = local_coupling * sr

I_l = self.Jll * sl - self.Jlr*sr + self.I_mot_l + self.I_o + J_N * c_0 + J_N * lc_0_l
I_r = self.Jrr * sr - self.Jrl*sl + self.I_mot_r + self.I_o + J_N * c_0 + J_N * lc_0_r
```
where J_N is some extra parameter describing excitatory recurrence. Someting along these lines?
What confuses me is that coupling is usually being added to the excitatory populations, but in WW each unit creates both: inhibitory and excitatory connections.

**Comment by dokato** [comment]
I fixed this code to match tVB default msec time scale and added the coupling as in the equations above for now.

**Comment by maedoc** [comment]
This looks fine to me, and the details of coupling should be finalized by using the model in a network and analyzing the results, so we can merge this now and revise the coupling terms later if required.

**Comment by maedoc** [comment]
@dokato thx!

**Pull request merged**
