### PR TITLE
add supHopf model

### PR DESCRIPTION
**Pull request by JulieCB**
Hello everybody,

I implemented the normal form of the supercritical Hopf bifurcation long time ago and as some people are interested it's time to make it available for everyone.

I did a small python notebook as well with phase plane and simple simulation. I will update it in the next days and create another pull request.

Thanks.

Best, Julie

### CODE REVIEW

**Comment by maedoc** [comment]
Thanks! As there are multiple models in this module, with multiple Numba dfuns, can you rename your `_numba_dfun` to `_numba_dfun_suphopf` or similar?

Otherwise it looks fine to me

**Comment by JulieCB** [comment]
Hi Marmaduke,

I just realized that I forgot to update also the name of the Numba dfuns when it's called in the dfun function. How should I proceed now you merge it?

Thanks.
Julie

**Comment by maedoc** [comment]
just push another commit and we'll merge it

**Comment by maedoc** [comment]
push another commit to your `supHopf_model` branch

**Pull request merged**
