### PR TITLE
Fix bug in Wilson-Cowan model

### PR DESCRIPTION
**Pull request by lionelkusch**
Add the condition of S_i(0)=0

### CODE REVIEW

**Comment by lionelkusch** [comment]
In the sigmoid, the authors mention a transformation of the function sigmoid:
"The first of these requirements is readily fulfilled by transforming Se and Si so
that Se(0) = Si(0) = 0. Given any sigmoid function, this may be done by subtracting S(0) from the original function."

In this case without external condition, the model return to zero and not to another value.
before the modification : 
before_modification

after the modification :
after_modification

**Comment by pausz** [comment]
The paper @lionelkusch refers to is the original  1972 "Excitatory and Inhibitory interactions in localized populations of model neurons". Specifically Eq. (15) in page 11. 

@lionelkusch Thanks for pointing this out.
+ Could you please add images of the phase plane before and after the changes? 
+ Additionally could you show that after the changes the I=0 and E=0 when P=0 and Q=0 are a steady state of the model? You could use the parameters in Fig. 4 of Wilson and Cowan (1972) and as bonus add this case to the model's docstring. 

+ After the changes, do the parameters in Table I of the model's docstring still reproduce Figure A1 in  Daffertshofer and van Wijk (2011)?  

The implementation of many models in TVB (eg, Wilson and Cowan and Jansen and Rit)  is not based on a single paper, but in several publications. As a result, the equations in the code may not reflect those published in the original work. I'm not saying this isn't a bug, but I first would like to have a better overview of how this change affects the phase space of the model itself  and the dynamics when this model is coupled. 

@liadomide I can help with this issue.

**Comment by maedoc** [comment]
> Could you please add images of the phase plane before and after the changes?

@lionelkusch there's an interactive phase plane visualizer that works in the Jupyter notebook w/ `%pylab nbagg`; ideally it'll only take a minute to get it done.

> The implementation of many models in TVB (eg, Wilson and Cowan and Jansen and Rit) is not based on a single paper, but in several publications.

In any case, despite any errors present, in our standard approach to bugs in models, an option should be provided to make it easy to obtain the previous, if incorrect, behavior in order to reproduce results.  For example, in [another model](https://github.com/the-virtual-brain/tvb-library/blob/trunk/tvb/simulator/models/stefanescu_jirsa.py#L584) we have 
```python
    def update_derived_parameters(self, corrected_d_p=True):
```
allowing a user to set the correction to `False` in the interest of reproducing results from older version of TVB. @lionelkusch I suggest adding a `Bool` parameter to the model with the correction, with a default of `True` and setup the necessary `if` `else` in the code.

**Comment by lionelkusch** [comment]
> In any case, despite any errors present, in our standard approach to bugs in models, an option should be provided to make it easy to obtain the previous, if incorrect, behavior in order to reproduce results.

@maedoc I add this option in the new commit.

**Comment by lionelkusch** [comment]
%pylab nbagg
from tvb.simulator.plot.phase_plane_interactive import PhasePlaneInteractive
import tvb.simulator.lab as lab
import numpy as np
from wilson_cowan import WilsonCowan
heunint = lab.integrators.HeunDeterministic()
ppi_fig=PhasePlaneInteractive(model=WilsonCowan(),integrator=heunint)
ppi_fig.show()

**Comment by lionelkusch** [comment]
@pausz I create the different figure
> Could you please add images of the phase plane before and after the changes?

before : 
before_init_interactive_phase-plane _wilsoncowan___--___heundeterministic
after :
after_init_interactive_phase-plane _wilsoncowan___--___heundeterministic

The next figures are a better view of the same phase-plane.

> Additionally could you show that after the changes the I=0 and E=0 when P=0 and Q=0 are a steady state of the model? You could use the parameters in Fig. 4 of Wilson and Cowan (1972)
10-figure3-1

before:
before_interactive_phase-plane _wilsoncowan___--___heundeterministic
after:
after_interactive_phase-plane _wilsoncowan___--___heundeterministic

In this case, only the modified model reproduce the figure of the Wilson-Cowan paper.

> After the changes, do the parameters in Table I of the model's docstring still reproduce Figure A1 in Daffertshofer and van Wijk (2011)?
fninf-05-00006-a001

before:
before_daffertshofer_interactive_phase-plane _wilsoncowan___--___heundeterministic
after:
after_daffertshofer_interactive_phase-plane _wilsoncowan___--___heundeterministic

In this case, only the original model reproduce the figure. 

So there are three different cases to solve this problem :
 - add another variable to chose: if the user wants to translate or not the sigmoid
 - don't make modifications because the actual model is the best. I think it will be better to change a little the model's docstring
 -make the modification I propose

@pausz What do you think?

**Comment by maedoc** [comment]
@lionelkusch thanks for the extra figures.  I would prefer that the default reproduce figures from Wilson & Cowan paper as this is the name of the model.  If you can provide some documentation in the model docstring on parameter configuration to reproduce the figure from the Daffertshofer and van Wijk paper, please do so (perhaps just setting the Boolean, IIUC?)

**Comment by lionelkusch** [comment]
I am sorry I take time before to do this modification. 
With the modification, we can reproduce all the figure we talk before. 
By default : (Fig. 4 of Wilson and Cowan (1972))
default

If we  change the parameter, we can reproduce the Figure A1 in Daffertshofer and van Wijk (2011) : 
daffertshofer

I modify the docstring with the parameter for this two cases.

**Comment by lionelkusch** [comment]
When I modify the model, I remark that some parameters are the same. 
For me, the parameter alpha_e/i and a_e/i are the same. 
And it's similar for the parameter theta_e/i and b_e/i.
If I am not wrong the only difference is that they come from different papers but they are used in order to parameter the logistic curve.

@pausz : Can you give me your opinion about this?
Thank you in advance.

**Comment by maedoc** [comment]
@lionelkusch not sure what you mean by same, they parametrize the two populations, in the same way.  Maybe you can state the problem more explicitly?

**Comment by lionelkusch** [comment]
@maedoc , I will try to explain more explicitly.
In Wilson and Cowan (1972), they use the parameters: a_e/i and b_e/i for parametrizing the sigmoid function. 
In the Daffertshofer and van Wijk (2011), they use the parameters alpha_e/i and theta_e/i for parametrizing the sigmoid function.
For me, these variables are the same, only the notation of the two papers is different. Thus I propose you to chose one of the two systems of variables for the model.

**Comment by maedoc** [comment]
@lionelkusch if its just a question of variable names, let us keep the ones already in TVB, at least for the pre-existing model.  For your new model, do as you like.  What's left to close this PR, please?

**Comment by maedoc** [comment]
No response I will assume we can close this PR.  For multiple papers with different notation, we should keep the original one from the first paper, so we stick with the Wilson Cowan notation.

**Pull request closed without merging**
