### PR TITLE
Tsv vis - better error handling and more data from server

### PR DESCRIPTION
**Pull request by rparcus**
Hello all,

here are the latest changes we discussed about.
The errors are being written to the logs directly while on the client side the warning messages are working just as expected thanks to the last commits to the framework.

The easiest way I've found to handle the numpy vs. JSON problem was to pass the data as Strings to the server.

### CODE REVIEW

**Comment by maedoc** [comment]
Unless @liadomide says otherwise, I think it is sufficient to raise an exception directly, and the exception will be logged by the framework, so you may be able to skip the log message.

I would have used the builtin `ValueError` exception type for each of these, I think.

Could you try pep8 formatting? If you `pip install autopep8` and `autopep8 -i path/to/file.py`, it will do it for you.

Do you need to convert the statistics to str here?

**Comment by liadomide** [comment]
Logging a warning on the server side, right before you raise the exception, is optional. We do not do it, as a habit in TVB, but it is your decision, @quiuquio, to do it or not. Indeed the framework will later log this exception before returning the error towards the client call. 

I agree with @maedoc that raising Exception() directly is not recommended. 
I would prefer using tvb.basic.traits.exceptions.ValidationException() 

pep8 formatting is highly recommended.

as for the use of str(), they must have been added because numpy float32 is not serializable. To overcome this one should converts numpy scalars to python floats.

**Comment by rparcus** [comment]
Regarding the `str()`:
I tried to parse the statistics directly to `float()`, but I probably did something wrong in the process (forgot to restart, forgot some variable, etc) . I went back to it and it is working as it shoul :) .
Regarding error handling:
In my last commit I changed things so that we are now using `tvb.basic.traits.exceptions.ValidationException()`.
This are two examples of what happens in the logs in case of error:

```
2014-08-12 12:20:26,047 - ERROR - tvb.interface.web.controllers.decorators - An unexpected exception appeared
Traceback (most recent call last):
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/decorators.py", line 108, in deco
    return func(*a, **b)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/decorators.py", line 85, in deco
    result = func(*a, **b)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/decorators.py", line 152, in deco
    return func(*a, **b)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/flow_controller.py", line 547, in read_datatype_attribute
    result = dataset(**kwargs)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-library/tvb/datatypes/time_series_framework.py", line 348, in get_volume_view
    raise exceptions.ValidationException(msg)
ValidationException: Time indexes out of boundaries: from 5000 to 176
2014-08-12 12:22:06,985 - ERROR - tvb.interface.web.controllers.decorators - An unexpected exception appeared
Traceback (most recent call last):
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/decorators.py", line 108, in deco
    return func(*a, **b)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/decorators.py", line 85, in deco
    result = func(*a, **b)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/decorators.py", line 152, in deco
    return func(*a, **b)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-framework/tvb/interfaces/web/controllers/flow_controller.py", line 547, in read_datatype_attribute
    result = dataset(**kwargs)
  File "/home/quiuquio/gsoc/TVB_Distribution/tvb-library/tvb/datatypes/time_series_framework.py", line 374, in get_voxel_time_series
    raise exceptions.ValidationException(msg)
ValidationException: Coordinates out of boundaries: [x,y,z] = [321, 1, 1]
```

All the info I would like to store for the user is there but is it normal to have the error being called like this:
`ERROR - tvb.interface.web.controllers.decorators - An unexpected exception appeared` ?

**Comment by liadomide** [comment]
Text "An unexpected exception appeared" is what our decorator for AJAX calls is adding before the actual exception.

**Pull request merged**
