### PR TITLE
Tsv visTime series vis + volume time series vis [preview] - library

### PR DESCRIPTION
**Pull request by rparcus**
This is needed by pull request https://github.com/the-virtual-brain/tvb-framework/pull/12

### CODE REVIEW

**Comment by liadomide** [comment]
Could you please remove the recently added "print" calls from the code ?

**Comment by pausz** [comment]
Using the logger -LOG.error- could a be possibility.

**Comment by liadomide** [comment]
Actually the entire sequence: raise Exception, immediate catch and print, then pass is a bit strange. 
What is the purpose of these?

**Comment by maedoc** [comment]
@quiuquio several times you've written

``` python
try:
    sh = get_thing()
    if test_on_sh:
        raise Exc
except Exc as e:
    print e(msg)
    pass
```

which is fully equivalent to, using logging instead of `print`

``` python
sh = get_thing()
if test_on_sh:
    log.warning(msg)
```

Can you use the simpler version here?

**Comment by pausz** [comment]
@quiuquio 

To get the logger, add the following import at the beginning of the file.

```
from tvb.basic.logger.builder import get_logger
LOG = get_logger(__name__)
```

**Comment by liadomide** [comment]
As discussed in today's call. We will accept this pull request, but a fix on the python side should soon follow, to cover this exception handling that we just discussed.

**Pull request merged**
