### PR TITLE
added matplotlib surface plotting routines

### PR DESCRIPTION
**Pull request by JohnGriffiths**
Some examples in the docstring; extended examples in gist notebook here

http://nbviewer.jupyter.org/gist/anonymous/c5dcba108b4a081e32cc0998139b6304

Will put a version of this notebook in the demos when the code is ready.

### CODE REVIEW

**Comment by maedoc** [comment]
Looks good!

**Comment by maedoc** [comment]
@JohnGriffiths hey sorry this sunk like a dead rock in my inbox. I'm pushing into the sprint for our upcoming BCW release, since I'm going to revise a bunch of documentation and docs issues and get our rest state tutorial online as well. 

http://req.thevirtualbrain.org/browse/TVB-2135

Are you gonna be at BCW in a few weeks?

**Comment by JohnGriffiths** [comment]
Hey.

No worries.

So what's status of the rest state tutorial? I think we really need to
bring that up to the quality of the epileptor examples.

Yes will be @ BCW & HBM.

j

On 8 June 2016 at 05:49, marmaduke woodman notifications@github.com wrote:

> @JohnGriffiths https://github.com/JohnGriffiths hey sorry this sunk
> like a dead rock in my inbox. I'm pushing into the sprint for our upcoming
> BCW release, since I'm going to revise a bunch of documentation and docs
> issues and get our rest state tutorial online as well.
> 
> http://req.thevirtualbrain.org/browse/TVB-2135
> 
> Are you gonna be at BCW in a few weeks?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/the-virtual-brain/tvb-library/pull/58#issuecomment-224542021,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAYSAqSjpsJ7QoLGjA3D-J5wqUjDY-l8ks5qJpApgaJpZM4IQ_Fw
> .

## 

Dr. John Griffiths

Post-Doctoral Research Fellow

Rotman Research Institute, Baycrest

Toronto, Canada

and

Honorary Associate

School of Physics

University of Sydney

**Comment by maedoc** [comment]
@JohnGriffiths I'm going to integrate this directly on SVN since we're moving quickly for the upcoming release.

**Comment by maedoc** [comment]
@JohnGriffiths hi sorry I forgot about this, should we continue the PR?  can you check it works and maybe reformat (I saw some 2 space indented stuff there)

(:beer: for @i-Zaak for digging this out!)

**Comment by JohnGriffiths** [comment]
Ok i'll take a look. 

Also need to double check the rotations are correct; I seem to recall seeing some inconsistencies. 

Do you know if all of the tvb surfaces and connectivities have the same orientation?

**Comment by maedoc** [comment]
@JohnGriffiths bump.  can you update this or close it?

**Comment by maedoc** [comment]
@JohnGriffiths we're going to start porting our 3d stuff to vtk.  if you want to help or follow it's starting at [TVB-2603](https://req.thevirtualbrain.org/browse/TVB-2603)

**Pull request closed without merging**
