### PR TITLE
add support of subcortical regions for seeg monitor

### PR DESCRIPTION
**Pull request by timpx**
in the spirit of what Paula did in surfaces_scientific.py, i.e. assuming subcortical regions are in the region mapping

### CODE REVIEW

**Comment by maedoc** [comment]
@timpx should we merge this ?

**Comment by timpx** [comment]
yes, as long as we keep on with @pausz fix for subcortical regions, this PR is valid.
Not tested extensively though

**Comment by maedoc** [comment]
OK. Would be nice to have some tests.

**Comment by maedoc** [comment]
This shouldn't be a problem once the current refactor is done.

**Pull request closed without merging**
